name: Create and publish a Docker image, and deploy on server

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
    tags:
      - v*

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

env:
  IMAGE_NAME: angularwebsite
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extracts metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ (steps.meta.outputs.labels == github.event.repository.default_branch) && 'latest' || steps.meta.outputs.labels }}

  deploy:
    if: ${{ false }}
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: angular-website
    permissions:
      packages: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy to Digital Ocean using ssh
        uses: appleboy/ssh-action@v0.1.4